# Select image from https://hub.docker.com/_/php/
image: php:7

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install system deps
- apt-get update -yqq
- apt-get install git zlib1g-dev -yqq

# Install modules
- docker-php-ext-install zip

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

test:php7:
  image: php:7
  script:
  - vendor/bin/phpunit
