version: '3.4'

services:
    centrala:
        image: macieklewkowicz/centrala
        build: .
        volumes:
          - ./app:/var/www/html/app
          - ./bootstrap:/var/www/html/bootstrap
          - ./public:/var/www/html/public
          - ./tests:/var/www/html/tests
        env_file:
            - .env
        environment:
            - VIRTUAL_HOST=centrala.local
        networks:
            - web

    zakupki:
        image: macieklewkowicz/zakupki
        env_file:
            - .env
        environment:
            - API_URL
            - VIRTUAL_HOST=zakupki.local,localhost
        networks:
            - web

    grocy:
        image: linuxserver/grocy
        container_name: grocy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Warsaw
            - VIRTUAL_HOST=grocy.local
        volumes:
            - ./etc/grocy/config:/config
        networks:
            - web

    ingress:
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./etc/nginx-proxy/cert:/etc/nginx/certs
        ports:
            - 80:80
            - 443:443
        networks:
            - web

volumes:
    certs:
networks:
    web:
