version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./public:/var/www/html/public
      - ./tests:/var/www/html/tests
  web:
    image: nginx
    ports:
      - 9080:80
    volumes:
      - ./dev/docker/nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./public:/var/www/html/public
    depends_on:
      - app
